_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 11
                - 30
                - 41
                - 49
                - 55
                - 95
            "2":
                - 1
                - 11
                - 30
                - 41
                - 49
                - 55
                - 95
            "3":
                - 16
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.7
            "6": 4.49.0
            "8":
                - 5
            "12": 0.19.7
            "13": linux-x86_64
allowed_local_media_path:
    value: ""
code_revision:
    value: null
disable_latency_logging:
    value: false
disable_logit_logging:
    value: false
disable_mm_preprocessor_cache:
    value: false
disable_sliding_window:
    value: false
dtype:
    value: torch.bfloat16
enable_sleep_mode:
    value: false
encoder_config:
    value: null
enforce_eager:
    value: true
generation_config:
    value: null
has_inner_state:
    value: false
hf_config:
    value: |
        MixtralConfig {
          "_name_or_path": "mistralai/Mixtral-8x7B-v0.1",
          "architectures": [
            "MixtralForCausalLM"
          ],
          "attention_dropout": 0.0,
          "bos_token_id": 1,
          "confidence_proxy": "diff",
          "eos_token_id": 2,
          "grouping_mechanism": "threshold",
          "head_dim": 128,
          "hidden_act": "silu",
          "hidden_size": 4096,
          "initializer_range": 0.02,
          "intermediate_size": 14336,
          "max_position_embeddings": 32768,
          "model_type": "mixtral",
          "num_attention_heads": 32,
          "num_experts_per_tok": 2,
          "num_experts_to_keep": 4,
          "num_hidden_layers": 32,
          "num_key_value_heads": 8,
          "num_local_experts": 8,
          "output_router_logits": false,
          "policy": "do-nothing",
          "ranking_policy": "high_confidence",
          "rms_norm_eps": 1e-05,
          "rope_theta": 1000000.0,
          "router_aux_loss_coef": 0.02,
          "router_jitter_noise": 0.0,
          "sliding_window": null,
          "threshold_percentile": 0.25,
          "tie_word_embeddings": false,
          "top_x": 2,
          "torch_dtype": "bfloat16",
          "transformers_version": "4.49.0",
          "use_cache": true,
          "vocab_size": 32000
        }
hf_text_config:
    value: |
        MixtralConfig {
          "_name_or_path": "mistralai/Mixtral-8x7B-v0.1",
          "architectures": [
            "MixtralForCausalLM"
          ],
          "attention_dropout": 0.0,
          "bos_token_id": 1,
          "confidence_proxy": "diff",
          "eos_token_id": 2,
          "grouping_mechanism": "threshold",
          "head_dim": 128,
          "hidden_act": "silu",
          "hidden_size": 4096,
          "initializer_range": 0.02,
          "intermediate_size": 14336,
          "max_position_embeddings": 32768,
          "model_type": "mixtral",
          "num_attention_heads": 32,
          "num_experts_per_tok": 2,
          "num_experts_to_keep": 4,
          "num_hidden_layers": 32,
          "num_key_value_heads": 8,
          "num_local_experts": 8,
          "output_router_logits": false,
          "policy": "do-nothing",
          "ranking_policy": "high_confidence",
          "rms_norm_eps": 1e-05,
          "rope_theta": 1000000.0,
          "router_aux_loss_coef": 0.02,
          "router_jitter_noise": 0.0,
          "sliding_window": null,
          "threshold_percentile": 0.25,
          "tie_word_embeddings": false,
          "top_x": 2,
          "torch_dtype": "bfloat16",
          "transformers_version": "4.49.0",
          "use_cache": true,
          "vocab_size": 32000
        }
is_attention_free:
    value: false
is_hybrid:
    value: false
logit_logging_frequency:
    value: 5
logits_processor_pattern:
    value: null
max_logprobs:
    value: 20
max_model_len:
    value: 32768
max_seq_len_to_capture:
    value: 8192
mixtral_config_file:
    value: /storage/home/hcoda1/4/vgupta345/scratch/ksinha45/prowl_mlsys/prowl/mixtral_configs/none-none-2.json
mm_processor_kwargs:
    value: null
model:
    value: mistralai/Mixtral-8x7B-v0.1
multimodal_config:
    value: null
num_experts:
    value: 8
override_neuron_config:
    value: null
pooler_config:
    value: null
quantization:
    value: null
revision:
    value: null
rope_scaling:
    value: null
rope_theta:
    value: null
seed:
    value: 0
served_model_name:
    value: mistralai/Mixtral-8x7B-v0.1
skip_tokenizer_init:
    value: false
supported_tasks:
    value:
        - classify
        - generate
        - reward
        - score
        - embed
task:
    value: generate
tokenizer:
    value: mistralai/Mixtral-8x7B-v0.1
tokenizer_mode:
    value: auto
tokenizer_revision:
    value: null
truncation_side:
    value: left
trust_remote_code:
    value: false
use_async_output_proc:
    value: false
